language: objective-c
 
branches:
 only:
 - master
    
xcode_workspace: Emome.xcworkspace
xcode_scheme: EmomeTests,EmomeUITests 
osx_image: xcode7
xcode_sdk: iphonesimulator9.0

script:
- xcodebuild clean build test -workspace Emome.xcworkspace -scheme Emome -sdk iphonesimulator9.0 -destination "platform=iOS Simulator,name=iPhone 6,OS=9.0" dONLY_ACTIVE_ARCH=NO
